// This file is auto-generated by trix bindgen.

import {
    TRPClient,
    type ArgValue,
    type ClientOptions,
    type SubmitParams,
    type ResolveResponse,
} from "tx3-sdk/trp";


export const DEFAULT_TRP_ENDPOINT = "http://localhost:3000/trp";

export const DEFAULT_HEADERS = {
};

export const DEFAULT_ENV_ARGS = {
};

export type PlaceOrderParams = {
    offeredAmount: ArgValue;
    offeredAssetName: ArgValue;
    offeredAssetPolicy: ArgValue;
    owner: ArgValue;
    recipientPaymentKey: ArgValue;
    requestedAssetAmount: ArgValue;
    requestedAssetName: ArgValue;
    requestedAssetPolicy: ArgValue;
}

export const PLACE_ORDER_IR = {
    bytecode: "0d03000106736f757263650d0206736f757263650d01056f776e6572050c010d01146f6666657265645f61737365745f706f6c696379040d01126f6666657265645f61737365745f6e616d65040d010e6f6666657265645f616d6f756e74020000010f00091c02e590a0fbb9edbd3b8f06f5cd162370f337cea9e7d3d74657ec73920300030300020d01167265717565737465645f61737365745f706f6c696379040d01147265717565737465645f61737365745f6e616d65040d01167265717565737465645f61737365745f616d6f756e74020300020300010d0115726563697069656e745f7061796d656e745f6b6579040300010300010300010d0115726563697069656e745f7061796d656e745f6b6579040c010d01146f6666657265645f61737365745f706f6c696379040d01126f6666657265645f61737365745f6e616d65040d010e6f6666657265645f616d6f756e7402000000000000",
    encoding: "hex",
    version: "v1alpha7",
};

export type SwapParams = {
    offeredAmount: ArgValue;
    offeredAssetName: ArgValue;
    offeredAssetPolicy: ArgValue;
    orderRef: ArgValue;
    recipient: ArgValue;
    requestedAmount: ArgValue;
    requestedAssetName: ArgValue;
    requestedAssetPolicy: ArgValue;
    trader: ArgValue;
}

export const SWAP_IR = {
    bytecode: "0d030002056f726465720d02056f726465720f00091c02e590a0fbb9edbd3b8f06f5cd162370f337cea9e7d3d74657ec7392000d01096f726465725f72656607030000036761730d02036761730d0106747261646572050e010d030c010d01167265717565737465645f61737365745f706f6c696379040d01147265717565737465645f61737365745f6e616d65040d01107265717565737465645f616d6f756e74020000020d0109726563697069656e7405000c010d01167265717565737465645f61737365745f706f6c696379040d01147265717565737465645f61737365745f6e616d65040d01107265717565737465645f616d6f756e74020d010674726164657205000c010d01146f6666657265645f61737365745f706f6c696379040d01126f6666657265645f61737365745f6e616d65040d010e6f6666657265645f616d6f756e7402000000000000",
    encoding: "hex",
    version: "v1alpha7",
};

export class Client {
    readonly #client: TRPClient;

    constructor(options: ClientOptions) {
        this.#client = new TRPClient(options);
    }

    async placeOrderTx(args: PlaceOrderParams): Promise<ResolveResponse> {
        return await this.#client.resolve({
            tir: PLACE_ORDER_IR,
            args,
        });
    }
    async swapTx(args: SwapParams): Promise<ResolveResponse> {
        return await this.#client.resolve({
            tir: SWAP_IR,
            args,
        });
    }


    async submit(params: SubmitParams): Promise<void> {
        await this.#client.submit(params);
    }
}

// Create a default client instance
export const protocol = new Client({
    endpoint: DEFAULT_TRP_ENDPOINT,
    headers: DEFAULT_HEADERS,
    envArgs: DEFAULT_ENV_ARGS,
});
