[protocol]
name = "cardano-dev-workshop"
scope = ""
version = "0.0.0"
description = ""
main = "main.tx3"

[registry]
url = "https://registry.dgram.io"

[profiles.devnet]
chain = "CardanoDevnet"

[[wallets]]
name = "alice"
random_key = true

[[wallets]]
name = "bob"
random_key = true

[profiles.preview]
chain = "CardanoPreview"

[profiles.preprod]
chain = "CardanoPreprod"

[profiles.mainnet]
chain = "CardanoMainnet"

[[bindings]]
plugin = "typescript"
output_dir = "./offchain"
